export const AJAX_CALL_BEGIN = 'AJAX_CALL_BEGIN'
export const AJAX_CALL_SUCCESS = 'AJAX_CALL_SUCCESS'
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR'

export const COUNTER_INCREMENT = 'COUNTER_INCREMENT'
export const COUNTER_DECREMENT = 'COUNTER_DECREMENT'

export const GET_NEWS_SUCCESS = 'GET_NEWS_SUCCESS'

export const YOUTUBE_SEARCH_SUCCESS = 'GET_YOUTUBE_SEARCH_SUCCESS'
